### ISSUE TITLE
File size reduction

### ISSUE THREAD

**Issue by arianaa30** [facebook/transform#13]
I've just applied the transform into a 1-minute equirectangular 360 video which I received here: 
http://cloud-mobile.360heros.com/producers/4630608605686575/1816573510412126/video/video_13a58875cc235e11f295bd5ac297d666_output_2k.mp4

The video is 1920 × 960 resolution, H264 AAC encoded, and the output is 1440x960 MPEG-4 AAC encoded file. I was wondering about the huge file size reduction! The original file was 123MB and now it is almost 10MB. Can you help me to understand what is going on? Why is the size reduction so much?! Maybe one of the options I've selected as below messes with something?!

I used the exact command you provided as example:
`ffmpeg -i input.mp4 -vf transform='input_stereo_format=MONO:w_subdivisons=4:h_subdivisons=4:max_cube_edge_length=512' output.mp4`

**Comment by boblaublaw** [comment]
Ffmpeg will recompress your input video using the settings specified on the ffmpeg command line, or defaults, if no settings are specified, as is the case with your command line.  The problem here is that the defaults are too aggressive for the videos you are working with.

If you want to reduce the compression, you will need to specify one of several options to tell ffmpeg how aggressively to compress your video.  This can be quite elaborate.  I would suggest you begin with specifying a constant quantizer using the -crf argument which is documented here:

https://trac.ffmpeg.org/wiki/Encode/H.264

It is important to understand that ffmpeg supports many codecs and that this documentation is for h.264.  Good luck!

**Comment by arianaa30** [comment]
Thank. Is there any options for ffmpeg to specify use the same parameters as the original video and not to compress?

And one more question: When I compare the two videos, it doesn't really look like they convert the equirectangular frame easily with splitting the frame into 6 regions, 4 in the middle 50%, bottom and top from the top 25% and bottom 25%, middle shift, and whatnots. Do they really just do this? The faces of cube do not really match such patterns; seems like much more transforms have been done!

![eq2cube](https://cloud.githubusercontent.com/assets/5509837/16026994/7571eb3c-3187-11e6-974c-266f548d5a0a.png)

![split](https://cloud.githubusercontent.com/assets/5509837/16027001/8719c008-3187-11e6-92a7-3eca0ec3d033.png)

**Comment by puffpio** [comment]
hey @arianaa30 wanted to bring up 2 points

1) there's not really a good way of ensuring the same quality as the original, as one doesnt really have a good idea of what the original was encoded at. you could do a "lossless" encode which would make sure the output is EXACT, but that would increase bitrate dramatically. if you want to encode something at high quality that tries to preserve the original but not go crazy on the bitrate, I suggest adding "-crf 18" to your command line
2) in your first post you used "max_cube_edge_length=512" as one of the settings, and stated your input video was 1440x960. For that input resolution the cube edge length of 512 is too large. it would be equivalent to upscaling the resolution of the video. to maintain the an equivalent resolution, try using "max_cube_edge_length=384"

**Comment by puffpio** [comment]
also, you're right, the reprojection is not as simple as cutting up the image into sections and distorting them. we actually reproject from equirectangular to spherical coordinates, and then project that onto a cube using a ray tracing-like algorithm

**Comment by arianaa30** [comment]
Thanks for the description. Yes, there should be some transforms involved because some cubes seem a bit rotated or something (a simple cut just over paint apps)

![1](https://cloud.githubusercontent.com/assets/5509837/16053062/058ba2fa-321c-11e6-872b-043f0bc758a5.png)
![2](https://cloud.githubusercontent.com/assets/5509837/16053061/058b413e-321c-11e6-97fc-45c35f06a77e.png)

Also I notice there are some anti-aliasing and distortion removal when the middle left-most portion is attached to the right-most part. I did some tests and noticed if I just do it as is, there are some edging problem that needs to be smoothed:

![test](https://cloud.githubusercontent.com/assets/5509837/16053268/ebf4b614-321c-11e6-9c0f-a356a9e36f39.png)

**Comment by boblaublaw** [comment]
I'm familiar with your source video and the car just isn't pointed at the 0 degree axis.  You could apply a rotation to fix this.

Your cube edges may be visible because the facebook transform filter and the player you are using are not aligned.  You can specify the "expand_coef" on the command line to tell transform how much to scale the cube faces.  The default is 101% scaling, you might try slight variations on that value.

**Comment by puffpio** [comment]
Yes, we default to a 1% buffer because you get some color bleeding between
cube very faces during the YUV to RGB conversion in hardware video decoding
engines

**Comment by arianaa30** [comment]
@puffpio Thanks for your info. I was just trying to follow your suggestions. I was wondering how you calculate the proper cube-edge-length that you suggested 384 for 1440x960 one? (Actually my input was 1920x960). Now I have a 4k video 3840 x 2160. So I'm guessing the proper edge should be around 1000?!

btw, my ffmpeg doesn't recognize -crf command. Any other ways to keep the same quality?

**Comment by puffpio** [comment]
since we divide the video horizontally into fourths you can just divide the
horizontal resolution by 4 most of the time
in regards to CRF...try to get a version of ffmpeg with x264 compiled in

**Comment by arianaa30** [comment]
Thanks!
