### ISSUE TITLE
expand_coef usage

### ISSUE THREAD

**Issue by abuisine** [facebook/transform#3]
Hi there !
Could you please explain the interest of expand_coef being at 1.01 by default ?
Is it because you do not map the resulting texture to a cubemap but rather to multiple planes in order to mitigate a clamp to edge setting ?

Cheers

**Comment by evgenykuzyakov** [comment]
The idea behind expand_coef is to add a margin for every face of the cube. So when we play a video, we don't need a texture copy to account for a cross texel interpolation between adjacent faces (e.g. when using external image texture on Android). Probably even a single texel would solve this issue for a good quality image. But since this is for videos, we might expect some artifacts closer to the edges. And the fixed relative 1% margin helps solve scaling problem, so you don't need to adjust your texture coordinates when the video source changes resolutions.

1.01 is pretty arbitrary number. Feel free to change it to what better fits your needs.

**Comment by abuisine** [comment]
Alright thanks !
